DROP TABLE IF EXISTS `product`;
CREATE TABLE `product` (
  `PRODUCT_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(500) DEFAULT NULL,
  `PRICE` double DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
);

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `USER_ID` int NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `DATE_OF_BIRTH` date DEFAULT NULL,
  `POSTCODE` varchar(45) DEFAULT NULL,
  `AREA` varchar(45) DEFAULT NULL,
  `TYPE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`)
);



DROP TABLE IF EXISTS current_order;

CREATE TABLE `current_order` (
  `ORDER_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
--  KEY `ProductID_idx` (`PRODUCT_ID`),
--  KEY `CustomerID_idx` (`CUSTOMER_ID`),
  CONSTRAINT `Customer` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `Product` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product` (`PRODUCT_ID`)
);


DROP TABLE IF EXISTS `droplist`;
CREATE TABLE `droplist` (
  `DROPLIST_ID` int NOT NULL AUTO_INCREMENT,
  `DRIVER_ID` int NOT NULL,
  `CUSTOMER_ID` int NOT NULL,
  PRIMARY KEY (`DROPLIST_ID`),
--  KEY `Driver` (`DRIVER_ID`),
--  KEY `Cst` (`CUSTOMER_ID`),
  CONSTRAINT `Cst` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `Driver` FOREIGN KEY (`DRIVER_ID`) REFERENCES `users` (`USER_ID`)
);

DROP TABLE IF EXISTS `invoice`;
CREATE TABLE `invoice` (
  `INVOICE_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`INVOICE_ID`),
--  KEY `Cust_idx` (`CUSTOMER_ID`),
  CONSTRAINT `Cust` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `users` (`USER_ID`)
);



DROP TABLE IF EXISTS `trolly`;
CREATE TABLE `trolly` (
  `TROLLY_ID` int NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` int NOT NULL,
  `PRODUCT_ID` int NOT NULL,
  `QUANTITY` int NOT NULL,
  PRIMARY KEY (`TROLLY_ID`),
--  KEY `ProductID_idx` (`PRODUCT_ID`),
--  KEY `CustomerID_idx` (`CUSTOMER_ID`),
  CONSTRAINT `CustomerID` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `users` (`USER_ID`),
  CONSTRAINT `ProductID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product` (`PRODUCT_ID`)
);



