@startuml
'https://plantuml.com/class-diagram

class JavaMail {
    +JavaMailSender getJavaMailSender()
}

class EmailServiceImpl {
    #emailSender: JavaMailSender
    +void sendSimpleMessage()
}

@enduml